[project]
name = "zombieonslaught2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-doubly-linked-list>=0.1.4",
    "pygame>=2.6.1",
]

[dependency-groups]
analytics = [
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
]
dev = [
    "pyrefly>=1.2.0",
    "ruff>=0.16.3",
]

[tool.ruff]
line-length = 120
exclude = ["spawn_rate_graph.py"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "COM812",
    "D101",
    "D102",
    "D107",
    "D203",
    "D212",
    "DTZ",
    "FBT001",
    "FBT002"
    ]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
